version: 2
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    groups:
      docker-security:
        applies-to: security-updates
        patterns:
          - "*"
      docker-version:
        applies-to: version-updates
        patterns:
          - "*"
